version: 2

machine:
  node:
    version: 8.2.0

dependencies:
  override:
    - npm install

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: bash .circleci/setup-heroku.sh
      - run: ember test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
