version: 2

jobs:
   build:
     docker:
       - image: circleci/node:8.9.1
     steps:
       - checkout
       - add_ssh_keys:
           fingerprints:
             - "b6:71:a2:f4:ed:88:b5:ab:da:a6:5f:0e:b2:83:20:f4"
       - run:
           name: Run Setup Script
           command: bash .circleci/setup-heroku.sh
       - run: echo "hello world"
       - run: npm install
       - run:
           curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
           sudo dpkg -i google-chrome.deb
           sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
           rm google-chrome.deb
       - run: /home/circleci/project/node_modules/.bin/ember test
       - run:
           name: Deploy Master to Heroku
           command: |  # this command is framework-dependent and may vary
             heroku git:remote -a overlook-property-group
             git push --force git@heroku.com:overlook-property-group.git HEAD:refs/heads/master
             heroku restart
