test:
  pre:
    - mkdir -p $CIRCLE_TEST_REPORTS/qunit
  post:
    - mkdir $CIRCLE_ARTIFACTS/log
    - mv $HOME/connect_api/log/* $CIRCLE_ARTIFACTS/log

deployment:
  staging:
    branch: master
    heroku:
      appname: overlook-property-group
