version: 2

machine:
  node:
    version: 8.2.0

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: npm install
      - run: ember test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
